### ISSUE TITLE
Notification from Object Graph

### ISSUE THREAD

**Issue by ordinaryorange** [mfidemraizer/trackerdog#6] opened 2016-07-18 10:55 UTC
Hey Matias,

Looking for a way to get notification from a proxied object graph when some property (or collection) deep in the graph changes. 
I know I can use the change tracker to look for changes, but I'm looking for more of an event to subscribe to.
One idea I had was to implement a custom interceptor which would bubble any INorifyPropertyChanged or ICollectionChanged events up (via a custom delegate) but I cant work out how to inject the new interceptor.
Am I on the right track, or would you recommend a different approach ?

**Comment by mfidemraizer** [comment] 2016-07-18 11:31
Hey ;)

So you want to attack an event handler at any level of an object graph to detect when a property changes.

I can think about two approaches:

1. The one you're talking about. We could fire a `PropertyChanged` event for both an own object's property and also for associated objects at any level. BTW, for me this has an issue. Since `INotifyPropertyChanged` event arguments just give *the property name which changed* we should receive something like `A.B.Text` which is awful. It would be better to get both the `PropertyInfo` and a reference to the object declaring the whole changed property.

2. Since the entire object graph shares the same object change tracker, whenever a change occur, the whole tracker is aware about it. I believe that the object change tracker should expose an event based on the following event arguments:

```
public class ObjectChangeEventArgs : EventArgs
{
        public ObjectChangeEventArgs(object owner, PropertyInfo changedProperty)
        {
        }
}
```

**Comment by mfidemraizer** [comment] 2016-07-18 11:57
You'll get surprised, but I've just implemented this feature. It was so easy. You can check how it works on the following test case: https://github.com/mfidemraizer/trackerdog/blob/master/TrackerDog.Test/SimplePropertyTest.cs#L265

Finally, since any property tracking implements `IObjectPropertyPropertyChangeTracking`, the whole event args gives you the exact property tracking that would give you the object change tracker but you won't need to poll it anymore since now you can get what you want using an event-based interceptor.

[Here you can check `IObjectPropertyChangeTracking` members](http://matiasfidemraizer.com/trackerdog/html/T_TrackerDog_IObjectPropertyChangeTracking.htm)

Let me know if this is enough for you or not :)

**Comment by ordinaryorange** [comment] 2016-07-18 11:58
Yes I think your option 2 is the better option if as you say that the entire object graph shares the same tracker.
But I wonder if the Event Delegate should be 
`public class ObjectChangeEventArgs : EventArgs
{
        public ObjectChangeEventArgs(object owner, IEnumerable<IObjectPropertyChangeTracking> changedProperties)
        {
        }
}`

which would capture both a change to a collection and any added properties to the new object being added (if it is being tracked also). The changedProperties args would be a summary of the most recent changes just detected. Thoughts ?

**Comment by mfidemraizer** [comment] 2016-07-18 12:05
I've re-updated the NuGet package, because I forgot to add the whole `targetObject` (owner object) of a given property.

About the other thing, I doubt that it could be implemented in an elegant way. Each property changes starts a change detection cycle. It would be awful to produce an in-memory change history or something like that.

IMHO, if I'm not mistaken, you should use `Changed` event in your own project to know which properties were changed previously:

```
List<IObjectPropertyChangeTracking> changedPropertyHistory = new ....

objectChangeTracker.Change += (sender, e) =>
{
       // Your code
      changedPropertyHistory.Add(e.PropertyTracking);
};
```

What do you think about this last thought?

**Comment by mfidemraizer** [comment] 2016-07-18 12:10
Well, now I need to go home and have lunch. BTW I'll stay waiting for your thoughts during this afternoon ;)

**Comment by ordinaryorange** [comment] 2016-07-18 13:00
Thanks for sneaking that event in that is absolutely perfect for my needs !
Not sure why but if I run your test method the event gets called just fine. But if I mod it to declare the trackable like this 
`var aa = new A();
	var bb = new B();
	var cc = new C();
	aa.B = bb;
	bb.C = cc;
	cc.Text = "hello";`

and then set `cc.Text = "goodbye"` after event wire up, the event does not fire.
Can you reproduce? I cant see why it shouldn't.

I'm going to add another issue before bed. Will check on your thoughts on things tomorrow.
Thanks for your help.

**Comment by mfidemraizer** [comment] 2016-07-18 20:21
@ordinaryorange  Hey! I could reproduce your problem. 

I understand that you're doing something like that:

```
var aa = new A(); 
var bb = new B(); 
var cc = new C(); 
aa.B = bb; 
bb.C = cc; 

aa = aa.AsTrackable();

// When you set this property using "cc" reference, ObjectChangeTracker.Changed event
// isn't fired, is it?
cc.Text = "hello";
```

I'm not sure if this is a bug or it's just how it should work after all. Let me explain what's my reasoning about this.

When you call `aa.AsTrackable()` you're saying *I want to track changes of this instance and also of its associations*. That is, TrackerDog sets object graph's association properties with proxied instances of the associated objects, but it can't auto-magically set arbitrary references like local variables. 

Thus, `cc` is still an non-tracked object while the instance of `C` associated to the `C` property of `B` has been set with a trackable `C` proxy.

Do you follow me? I believe that after all, it's not an issue, but I'm open to discuss it :)

**Comment by ordinaryorange** [comment] 2016-07-19 00:16
In the particular application that I'm working on, I only know about the root objects in the object graph. (i.e. the aa objects), but I need to know if something lower in the graph changes. I was hoping to be able to wire up to the `Changed` event on the aa objects and get notification when anything changes on their respective graphs.
You are absolutely right saying _I want to track changes of this instance and also of its associations_ but further qualify that with _can you let me know when any one of those associated instances detects a change_
I'm not sure what you mean by not being able to auto-magically set arbitrary references? I don't think we are doing that? If we set `cc.Text = "hello"` and then inspect the tracker from aa. The tracker shows me that indeed the `Text` property on object instance `cc` has changed. So if the tracker knows `cc` changed (which it should because `cc.Text` is marked as `virtual`) therefore should that change then be reported via the `Changed` event of the tracker ?

**Comment by mfidemraizer** [comment] 2016-07-19 06:30
For example, if you turn into *trackable* the whole `A`, `B`, `C` object graph as you described:

```
var aa = new A(); 
var bb = new B(); 
var cc = new C(); 
aa.B = bb; 
bb.C = cc; 

aa = aa.AsTrackable();
```
- `aa` will be a proxy.
- `bb` won't be a proxy, but `aa.B`  yes.
- `cc` won't be a proxy, but `bb.C` yes.

I mean that you can't exchange the object referenced by a variable without setting a new object on the whole reference. TrackerDog does it for the associations but, AFAIK, this can't cover setting the `C` trackable proxy on `cc`.

Do you understand what I mean?

**Comment by ordinaryorange** [comment] 2016-07-20 00:27
Ha, you are dead right. I was wandering off some imaginary yellow brick road...
I ran some code here to re-educate myself about what objects know what, and now things are clear for me. So yes Tracker Dog is doing the right thing, and there is no need to change him. If I use him the right way I'll get the deep notification I'm after. Thanks

**Comment by mfidemraizer** [comment] 2016-07-20 15:56
@ordinaryorange No problem! So we should close this issue!

**Closed by mfidemraizer** 2016-07-20 15:56 UTC
Labels: enhancement
