### ISSUE TITLE
Override of .Equals() on proxy needed ?

### ISSUE THREAD

**Issue by ordinaryorange** [mfidemraizer/trackerdog#9] opened 2016-07-22 12:08 UTC
Now I'm not sure if this is a bug, or the way things should be.
If I run the following code (_the .Dumps are because I've copied direct from Linqpad._)
``` c#
	TrackerDog.Configuration.TrackerDogConfiguration.TrackTheseTypes(Track.ThisType<A>());	
	ObjectIDGenerator gen = new ObjectIDGenerator();
	var o = new A();
	var olist = new List<A>();
	var trackable = o.AsTrackable();
	olist.Add(trackable);
	var oarray = new A[1];
	olist.CopyTo(oarray);
	olist[0].Equals(oarray.First()).Dump("Are Equal");
	o.GetHashCode().Dump("o hashcode");
	oarray[0].GetHashCode().Dump("o hashcode from array");
	bool n;
	gen.GetId(o, out n).Dump("o ID");
	gen.GetId(oarray[0], out n).Dump("o from array ID");
```
I get

**Are Equal**
False 
**o hashcode**
103653 
**o hashcode from array**
103653 
**o ID**
1 
**o from array ID**
2 

But if I comment out .AsTrackable() i get

**Are Equal**
True 
**o hashcode**
15193904 
**o hashcode from array**
15193904 
**o ID**
1
**o from array ID**
1 

Now I understand why, but the question is should the proxy return `True` on a shallow copy ? 
Given that the now 2 different proxies are pointing to the same underlying object I would say they should. What do you think ?

**Comment by mfidemraizer** [comment] 2016-07-22 12:35
I'm not sure now, but without checking the code I'm pretty sure that `GetHashCode` of proxies aren't overridden, or I don't remember at all. I'll give a look at this!

**Comment by mfidemraizer** [comment] 2016-07-22 12:48
I've already checked the code. If you look inside [`ChangeTrackableObjectMixin`](https://github.com/mfidemraizer/trackerdog/blob/master/TrackerDog/Mixins/ChangeTrackableObjectMixin.cs) class you'll see what's producing this situation:

`public override int GetHashCode() => Id.GetHashCode();`

The whole mixin which gets mixed with the whole run-time generated proxy needs an stable `GetHashCode` to allow Castle DynamicProxy to cache proxy class. 

Some month ago I faced some bug because each instantiation was a different proxy class so I decided to define an arbitrary and static `Id` on the mixin to overcome this issue.

Now I see that fix has that *con* you've described here. 

I'll take a look at how to solve this situation. Probably the best one is accessing the target's object `GetHashCode` (target object is the object being wrapped/proxy) only if it that method has been overridden. Otherwise, the bug of generating many proxy clases would arise again!

**Comment by mfidemraizer** [comment] 2016-07-22 17:55
@ordinaryorange Uhm, now I'm confused.

See the following code:

            A a = new A().AsTrackable();

            Assert.AreEqual(a, a);
            Assert.IsTrue(a.Equals(a));

Both equality checks are successful. Isn't this simple test equivalent to what you're doing in your code sample?

**Comment by mfidemraizer** [comment] 2016-07-22 21:55
BTW, I believe that it would be important to see what's your `A` class source code. I try to understand what's going on in your case...

**Comment by ordinaryorange** [comment] 2016-07-22 23:38
Here what an A class looks like
```
public class A
{
	public object MyProperty2 { get; set; }
}
```
And your above code snippet of yours is not equivalent. The issue arises because of the `Array.CopyTo()` method. Reading the docs on this method it performs a shallow copy of the objects into another array. I started to explain what I thought was going on under the hood but discovered a hole in my logic. So I need to do some more reading/experimenting. I'm pretty sure it is not the hashcode that is the problem, but the implementation of `.Equals()`. If you don't override it in _(I have not checked the code)_ Trackerdog then maybe it is a Castle issue. I'll see what I can find.

**Comment by mfidemraizer** [comment] 2016-07-23 06:57
Actually `Equals()` is overridden:

        public override bool Equals(object obj)
        {
            if (obj == null) return false;

            ChangeTrackableObjectMixin mixin = obj as ChangeTrackableObjectMixin;

            if (mixin == null) return false;

            return mixin.Id == Id;
        }

**Comment by mfidemraizer** [comment] 2016-07-23 07:06
It's strange but I can't reproduce your code behavior. In my case, everything is `true`:

            A a = new A().AsTrackable(); ;

            List<A> list = new List<A>();
            list.Add(a);

            A[] array = new A[1];

            list.CopyTo(array);

            Assert.AreEqual(list[0], array[0]);
            Assert.IsTrue(list[0].Equals(array[0]));
            Assert.AreEqual(a, list[0]);
            Assert.AreEqual(a, array[0]);

**Comment by mfidemraizer** [comment] 2016-07-23 07:12
I've even tried your exact code in a test case! And it's always `true`!

            var o = new A();
            var olist = new List<A>();
            var trackable = o.AsTrackable();
            olist.Add(trackable);
            var oarray = new A[1];
            olist.CopyTo(oarray);

            Assert.IsTrue(olist[0].Equals(olist.First())); // This assertion passes!

Could it be something with LINQPad?

**Comment by mfidemraizer** [comment] 2016-07-23 07:19
Uhm and I can also confirm that both overridden `GetHashCode` and `Equals` of `ChangeTrackableObjectMixin` aren't part of the whole proxy but used during proxy generation. 

If I override `A.GetHashCode()` or `A.Equals()` they get called. Their `ChangeTrackableObjectMixin` counterparts aren't part of the proxy type but they're used to correctly cache proxy types...

Let's see if you can give me some hint to reproduce your issue! Try it with Visual Studio Test instead of LINQPad and check if you get the same behavior...

**Comment by ordinaryorange** [comment] 2016-07-23 13:43
Ok, it's not a VS or Linqpad issue. Managed to get your code to fail in both
Added this to the top of your code. Can you confirm it is missing ? 
`TrackerDog.Configuration.TrackerDogConfiguration.TrackTheseTypes(Track.ThisType<A>());`
I think you are not generating proxies ! Just plain POCO's.

That's the first bit.
I had a look at the code and I can see that the `_id` of the mixin is just a `new Guid()`. If the Array.Copy() is performing a shallow copy of the object then the new instance in the destination array will be a different proxy because any call to the overridden equals will look at the Guid. (does this sound right ?)

The above is my best guess, but I have issues with the "shallow copy" of the CopyTo function. See my post I just put up on SO.
http://stackoverflow.com/questions/38542336/understanding-of-array-copyto-and-equals

**Comment by ordinaryorange** [comment] 2016-07-23 14:35
I see where I went wrong with the "shallow copy" understanding. The shallow copy is just on the array. So that discounts my previous idea.
However I just discovered that if we use `Trackable.Of<A>()` instead of the extension method `AsTrackable()` then the `Equals()' comparison of the first item in the List and the Array now returns True !!!
So now I have no ideas....
What does .AsTrackable() do different to Trackable.Of() ?
The latter is giving me what I'm expecting, so maybe it is the former with a bug ?

**Comment by mfidemraizer** [comment] 2016-07-24 08:02
@ordinaryorange Now I'm not at home and I can't verify your conclusions. BTW, tomorrow I'll give a look!

**Comment by mfidemraizer** [comment] 2016-07-24 20:17
In my case, it's generating the whole proxy and all assertions are still `true`:

![a](https://cloud.githubusercontent.com/assets/820748/17086196/52328eee-51ec-11e6-9288-46ee64fdf485.png)

**Comment by mfidemraizer** [comment] 2016-07-24 20:30
Now I've some doubts about your case, or, in other words, I've some facts

- `A` and `AProxy` *hash code* must be different unless  `A`  has overridden `GetHashCode()`.
- A given *proxy* is another instance. The non-proxied `A` instance is *wrapped* by the proxy so it's an expected behavior that both could have different hash codes unless `A` has overridden `GetHashCode()`.

I mean that `A` and `AProxy` in our scenario must have different hash codes.

What really destroys me is the **Are Equal: FALSE**. I can't get this behavior in my computer, even when I copy-paste your case!!! Are you sure that this is the result?

**Comment by ordinaryorange** [comment] 2016-07-25 00:04
I agree with your two points above, but that's not what the issue is. I have attached a VS project which clearly shows the problem. Nothing complex just 2 classes and 3 test methods to demonstrate the issue. 
When I run the tests here, Test 2 and 3 pass, and Test 1 fails. As you will see Test 3 does not use tracker dog at all, just a plain POCO. Test 2 Uses `Trackable.Of<A>();` and test 1 uses `.AsTrackable()`.

Can you run on your machine and see what you get ?
All three tests should pass, should they not ?
[Tests.gz](https://github.com/mfidemraizer/trackerdog/files/380569/Tests.gz)

**Comment by ordinaryorange** [comment] 2016-07-25 02:36
Further update, just added a 4th test to the project for a case that I missed. Test 4 also fails.
So the issue only seems to arise when a trackable proxy is created around an existing object.
I'll keep digging.
[Tests.gz](https://github.com/mfidemraizer/trackerdog/files/380697/Tests.gz)

**Comment by ordinaryorange** [comment] 2016-07-25 07:31
I totally agree with your items above, but they do not represent the issue. I've just spend all day on it, (some of the day going in circles) but I'm narrowing down the issue. At this stage I'm getting a different result from `.Equals()` and `Assert.AreEqual()`, and in one situation the proxy being added to a generic list is not equal to the `List[0]` object !!! Grr. Going home now, but keen to tackle it tonight. Will come back to your with more...This odd behavior is a doosy.

**Comment by mfidemraizer** [comment] 2016-07-25 12:26
@ordinaryorange Could you share again your current code to check it on my machine? I checked that you removed some comment where you put your code. 

Share your most recent code in order to assist you in finding some conclusion to this issue ;)

**Comment by ordinaryorange** [comment] 2016-07-25 12:54
Ok I've hit the wall. I have been over and over it and I need your eyes to have a look.
Here is where I am - 
I have made a specific VS project with 1 class containing 27 tests. Rather than copying code snippets from this thread, I have attached the whole solution for you to load and run on your machine. That will eliminate any possible variances.
The 27 tests are a matrix of 
1. Creating a plain POCO first, then once instantiated, then calling `.AsTrackable()`
2. Creating a Trackable via `.AsTrackable()`, but directly from the `new` call of the POCO
3. Creating a trackable via `Trackable.Of<>()`
4. Creating a Generic List and then adding the trackable to it and then asserting that the trackable and the zeroth index are equal
5. Copying the List to an array via the `CopyTo()` method and then asserting that the zeroth object in the list equals the zeroth object in the array
6. Asserting that the original trackable is equal to the zeroth object in the array
7. Asserting via the `AreEqual()` method
8. Asserting via the `AreSame()` method (reference equality)
9. Calling the `object.Equals()` method before then `Asserting.IsTrue()` on that result

On my machine these 6 test fail
![image](https://cloud.githubusercontent.com/assets/20490998/17101406/79d2cb90-52b3-11e6-8d22-bca1537f7274.png)

I have no idea why, I cant see a fault in any of the 6 tests. Other tests that are "logically" the same seem to pass. Some of your tests were just the same and you got passes.
Let me know what you find, it will probably be obvious....At minimum I hope you also get the same test failures. Thanks

[TestProject.gz](https://github.com/mfidemraizer/trackerdog/files/381512/TestProject.gz)

**Comment by mfidemraizer** [comment] 2016-07-25 13:36
@ordinaryorange Let's try to DESTROY the wall! I'll take a look at your code!

**Comment by mfidemraizer** [comment] 2016-07-25 14:11
Do you want to cry with me? If I run, for example, one of your tests cases `AsTrackableFromExistingA_ObjectEquals_aEqualsArray0`, I get the exact issue. 

Now cry: If I copy-paste the same code and I put it in TrackerDog's test project in a new test method, I get  `true`, `true`, `true`......... Now I'm going to investigate what's different on your and my project... Now I'm concerned about what's the wrong behavior!

**Comment by mfidemraizer** [comment] 2016-07-25 14:43
Ok! I found the difference that matters!

In TrackerDog's test project, there's no type that's being configured as *trackable* without providing *included properties*. In your case you're just configuring `A` with `Track.ThisType<A>()` and you want all properties to be trackable.

I'm going to investigate what's going on then!

**Comment by mfidemraizer** [comment] 2016-07-25 15:01
I've found another difference. When you not include properties explicitly, Castle DynamicProxy won't generate a new type called `AProxy` but it will stay as `A`.

In the other hand, even when the type isn't called as `AProxy` it's still a proxy because it can still track changes! I believe that, at least, now we're in the right direction to solve the issue...

**Comment by mfidemraizer** [comment] 2016-07-25 15:50
Ohh!! I believe I could detect what was going on!

Change-tracked properties are proxies thanks to a proxy generation hook I had to implement to avoid intercepting any property and then filtering them checking they're trackable or not.

Castle Dynamic Proxy provides *hooks* so cached proxy types will just intercept those method/properties that were elegible for interception during proxy type generation. 

When TrackerDog receives a trackable type which already selected which properties must be tracked for changes, the whole proxy generation hook will choice them and that's all. But when you don't provide one, the whole hook will return always `true` either if it's a property or even a regular method. 

This wasn't an issue because both in project's test and where I use TrackerDog I'm always including specific properties!

So, at the end of the day, I've changed the following if in the whole `SimplePropertyInterceptionHook` source code:

        public bool ShouldInterceptMethod(Type type, MethodInfo methodInfo)
        {
            // RETURN FALSE IF IT'S NOT A PROPERTY GETTER OR SETTER, THIS IS THE FIX
           // TO STOP OUR NIGHTMARE!
            if (!methodInfo.IsPropertyGetterOrSetter() || _skippedMethods.Contains(methodInfo))
                return false;

And it seems like the issue has been solved. BTW, now two tests from TrackerDog are failing. Once I fix them, I'll push a new NuGet package as 1.2.4 and we'll end this nightmare! :D

**Comment by mfidemraizer** [comment] 2016-07-25 16:11
@ordinaryorange Solved! 

I've already tried v1.2.4 on your tests and now they're all passing!

So... it wasn't easy to identify the underlying problem, but we did it!

Let me know if you find any other problem that may be related to this issue. Or it would be great to know if you find it *solved* to close this issue forever! :)

**Comment by ordinaryorange** [comment] 2016-07-26 09:20
Crowd Roars !!!!!!!!!!
Yep, ran it over the tests here and all pass.  Then uploaded new version in my app and not I'm getting what i'm expecting. Well Done. Thankyou !
I'm gald you found it it was a head scratcher for me.

**Comment by mfidemraizer** [comment] 2016-07-26 09:45
@ordinaryorange  hahaha, BTW, you said "not I'm getting what I'm expecting". Is this a typo and you mean that you got what you expect? ;)

**Comment by mfidemraizer** [comment] 2016-07-26 09:47
@ordinaryorange  It was also a head scratcher for me too, I had no easy way to know what was going on. What gave me the right direction was the fact that without including properties explicitly, the type wasn't `AProxy` but just `A`....

**Comment by ordinaryorange** [comment] 2016-07-26 10:51
Yep typo, all good. You can close this one.

**Comment by mfidemraizer** [comment] 2016-07-26 11:18
Nice! We're advancing then. I'll check the other issues as soon as possible to close them all too ;)

**Closed by mfidemraizer** 2016-07-26 11:18 UTC
Labels: bug
